<!DOCTYPE html>
<html lang=en> <head> <!-- @include('partials._headForIndex') @include('partials._head') --> <link rel="shortcut icon" href=../favicon.ico> <link rel=stylesheet type=text/css href=css/css/normalize.css> <link rel=stylesheet type=text/css href=css/css/demo.css> <link rel=stylesheet type=text/css href=css/css/component.css> <link href=http://fonts.googleapis.com/css?family=Raleway:200,400,800|Clicker+Script rel=stylesheet type=text/css> <link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css integrity=sha256-T2BVEQmlUCoftgGysWhy/vUjLn+SusHDt3mnXoGdPxY= crossorigin=anonymous> <link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/aos/2.1.1/aos.css.map> <link rel=stylesheet type=text/css href=css/circle/demo.css> <link rel=stylesheet type=text/css href=css/circle/common.css> <link rel=stylesheet type=text/css href=css/circle/style4.css> <link href=http://fonts.googleapis.com/css?family=Open+Sans:300,700 rel=stylesheet type=text/css>

<meta charset=utf-8> <title>Website Builder&Website Designer | Web Design</title> <link rel=canonical href=./index.blade.php> <meta name=viewport content=width=device-width,minimum-scale=1,initial-scale=1> <meta http-equiv=X-UA-Compatible content=IE=edge> <meta name=description content="The best website designer, website builder and website design solutions. Google friendly SEO, fast internet loading pagespeed, AccessTech.io and West Brown are the web design company just for you.  We are located in Wilmington, NC.  Learn more about our web development."> <meta name=keywords content="websites, website, design, builder, internet, marketing, ppc, designer, developer, development, custom, google, friendly, web, seo, management, wordpress, drupal, solution, app, wilmington, nc"> <meta name=google-site-verification content=E0dIcNs5_CN27MpHWntn7rv5HLUST-i5epp59fUsaPA> <meta name=msvalidate.01 content=9E083C7F7449311A96036DFB9C6DD4EF> <link rel=stylesheet href="{{ asset('css/app.css') }} "> <!-- Latest compiled and minified CSS --> <link rel=stylesheet href=https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css integrity=sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u crossorigin=anonymous> <!-- Fonts --> <link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css integrity=sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+ crossorigin=anonymous> <link rel=stylesheet href=https://fonts.googleapis.com/css?family=Lato:100,300,400,700> <script async custom-element=amp-carousel src=https://cdn.ampproject.org/v0/amp-carousel-0.1.js></script> <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript> <script async src=https://cdn.ampproject.org/v0.js></script>

<link rel=stylesheet href=https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css><script async src=https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js integrity=sha256-z6FznuNG1jo9PP3/jBjL6P3tvLMtSwiVAowZPOgo56U= crossorigin=anonymous></script><script async src=https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js integrity=sha256-399DNRyfIpWIy1ZV0KmEIIuIQ5sBHdLu9MBtVHrNtt8= crossorigin=anonymous></script> @include('partials._indexcss') <style amp-custom>
    a {
      color: black;
    }
    ul.ch-grid {
      margin: 0;
    }
  </style></head> <body> @include('partials._nav') <div class=demo-2> <div id=large-header class=large-header> <canvas id=demo-canvas></canvas> <!-- sep --> <div class=sep> <h1 class="main-title text-center" onload=myFunction() id=builder>Web Design by AccessTech.io</h1> </div><!-- /sep --> <h3 class="title text-center hidden-xs hidden-sm" onload=myFunction() id=build>Let Us Build An Awesome Website For You Today.</h3> </div> </div> <h3 class=text-center>You'll Be Glad You Selected Us!</h3> <!-- container --> <div class=container> <div class=row> <div class=col-md-4> <div class="wow slideInRight"> <ul class=ch-grid> <li> <a href=/solution> <div class="ch-item ch-img-1"> <div class=ch-info-wrap> <div class=ch-info> <div class="ch-info-front ch-img-1"></div> <div class=ch-info-back> <h3>Why Choose Us?</h3> <p>pattern by Josh Schott, View on Dribbble</p> </div> </div> </div> </div> </a> </li> </ul> </div> </div> <div class=col-md-4> <div class="wow slideInRight"> <ul class=ch-grid> <li> <a href=/pricing> <div class="ch-item ch-img-2"> <div class=ch-info-wrap> <div class=ch-info> <div class="ch-info-front ch-img-2"></div> <div class=ch-info-back> <h3>Go To Pricing</h3> <p>pattern by Jeremy Slagle, View on Dribbble</p> </div> </div> </div> </div> </a> </li> </ul> </div> </div> <div class=col-md-4> <div class="wow slideInRight"> <ul class=ch-grid> <li> <a href=/contact> <div class="ch-item ch-img-3"> <div class=ch-info-wrap> <div class=ch-info> <div class="ch-info-front ch-img-3"></div> <div class=ch-info-back> <h3>Please Contact AccessTech.io Today</h3> <p>Pattern by Dustin Leer, View on Dribbble</p> </div> </div> </div> </div> </a> </li> </ul> </div> </div> </div> </div><!-- /container --> <br> <!-- jumbotron --> <div class=jumbotron id=jumbo-black></div><!-- /jumbotron --> <!-- wilmington --> <div class=jumbotron> <p id=jumbo-p>AccessTech.io</p> <h3 class=text-center><a href=/contact id=footer-contact>Contact AccessTech.io</a>To Assist You With Your Web Design Needs.</h3> @include('partials._footer') </div> <script>
    new WOW().init();
</script> @include('partials._js') @include('partials._jsForIndex') </body> </html>